apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/X-BRAIN-CDO-09/PhanLeThanhHoang-aws-accelerator-p2.git # Chú ý: bạn cần thay đổi URL này trỏ đúng vào repository của bạn
    targetRevision: main
    path: cloud/w10/temp/eso # Chỉnh sửa đường dẫn này cho khớp với cấu trúc trong repo thật
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
