apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-cosign-signature
spec:
  images:
    - glob: "ghcr.io/**"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8qnfFLstbq5emhpniK1n9ppvq+of
          PkWZ0zyQ2m+8W+kzNbcHdWi4sf/iMsKy5cYZ0+RzTLtkVcSsszXFT+FS4Q==
          -----END PUBLIC KEY-----
