apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flipkart-mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/X-BRAIN-CDO-09/PhanLeThanhHoang-aws-accelerator-p2.git
    targetRevision: main
    path: cloud/w9/flipkart-mern/k8s/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: flipkart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
