apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-app-config
  namespace: counter-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  APP_VERSION: "v2"
  APP_NAME: "Counter App"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app-deploy
  namespace: counter-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: hofang42/counter-app:v2
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: counter-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: counter-app-svc
  namespace: counter-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: NodePort
  selector:
    app: counter-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
