apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-secret # K8s secret name to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: my-aws-secret # AWS Secrets Manager secret name (to be confirmed by user)
