---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-smtp-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgBBUoKY8+v6/X0/3BL1q7K4szjvBN3StTAM0SzP3hOSc/mCpvCA41nxFLjiCZj5PQyzoc+BjaCLqU4wBuvtnlKsvsnfbW0IaN6he/GL7qtEkB5ZJg84gyddxnbcLY0BDzOh+Q6YxEXyZT1saYAmUwZyCKzZa4fZXYa9Daw+cViU3Etwo6KrCa1P2duIcj6LsaII95vXML52CeFv86x8UQN6wZA7CUIjqlJ6Hpf/rNkuxsS1WmxnIGfmlh1fTV1oG6ZQa9B0Uy9Xhv3+hPo3jRl7Emr7NF1W++mUUn4vhF6oUf9sy1mt87JYcEpyZ9ZDoPujsuooW+UkR2KjfR13G1vTQdy4WoEz6sWTTyE1jjF++QNPUGY1T9D0Ii9Kj2qBerXubXG9Q5exkk1IIM2wK3DXYiC4me5rymXOJ/xFWMu2LSLCP+G8vV4FvAqV/ND4j0d6dH1V3vN5WtH3BFrZBGWVSbbX+KchCMJaigXvGar01z76npFs4wlzYO1HTMb7VIGzg0STfzg29k7qkPxnukqeB1lxeiWxzNS9TG1OBLcXDrFvzxldI9KW+zjKbN1a+EGfdAToZl8KR4ijs4dK3BOI/ES2FK3bu9dA7+dj1I60Wt45n9Q2pWAfQ2iPFjKZY3dxRCBphkW6pJQkB373AhKdlfQiAY4FUFH0r3SSLmRbY4Aq520XXvZQhv3mCINm+U6HnnjG68pPwE56yLqLwBgCJ2kGQFLpfYcilBqBr6DmexukrDEyi0yglz5vBLFGAwkKgBLsQe4cyL0IU02SeSzVcRy134o=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-smtp-credentials
      namespace: monitoring
    type: Opaque
