---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-smtp-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgCiLhYATiq5XV+WVgCcZgWBuo+QMLRs/55X8w43bylBy8mo3Q7UKNd738HXFIvsffXpAnXPv/msgZhb0n82i5+0S7Y6ID+SzL4t2QGABrl+DFXAadAUpIMDJ0WJTXfxO+9k1DJUzCyBsNc33Xcsdn2/xTU8nnwvTT7XajeZ/K12USAz2i9OzIGO2OS5rJ3YVBVXdghqg4LEaGKfl2u6jZ0ghshSQipQX4vfBPplO9Z9mJg0zakr7jYq2/V7p1o4B+JpFkyoc8w9xt7hQepaAlgaHWGFRNPtjqqz/agGjVLhaYUFstYLksny31ilGJgifF/qRjfbN+d78oQCrBqPdImH/JyvcTyhamFg/tZKDPOqRam1HadU6aj7sMJ/eY3uM6Pkv7FsnlvSkxVdQk7kEhHQ5PPtvMStX+aaffwhfTGg6urnltmPsZcAx0Ta2g7BA0Ukw964D/5wRTft9/j56mTMKbkaJMPqksnmSRS8rz6UCZdMMdSn6Hb3WdxPnTXK3g5mD5ScRRRUEsd17Tgm5FcPNEmbO/EM+zvArLPpnnIqavQnRRiybx9nXezZKhSEqrHwSkPI6IJ2hMgCiZpsbkpmHxF59D6zf4nwhE/U1y1KdKXyyvDz/KNNaq2yIg0s1eetWmkf1CcFZD/wHxchp0S+p1etzFuzAub+eM4HYUP6HvF3pxz2O5FxYTZLMbjv/ZL7ibtdt1Wvo+2py1mhz4dTys0PpCEykHqVdz6swsObWE9etE5hYbR45jrvnbyFrPgQbAJuwS9LJOHk+VEHmsuZu6XJ/dw=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-smtp-credentials
      namespace: monitoring
    type: Opaque
