---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-smtp-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgB031M9ufTpDtlrY8a6uyYXHoQkwsygrDwzMKPH/xitUtn9FCIBRnKNI71TE/fjRDjYloXjQNYLqoL7WclNSSdirEL8FTmW2LHirt0H29IQslrZBAtEb0KbTjkrwFbJymofAKXj89rim7gun8+YFsOHZnv0fhoJaqy1UzIk25Y3r9uFMt6xb16cmwHU7XdLT85FKEWf3+rRGSUPegyM6lBmx5V7cYxgc5DkwjJ92cSPmMxlw51tJ3O0V9bhr9zdiOnUMkSa5qXID4jrPh3z5PHyoX/ktt24qfzSH31Ih2GeLuHHn9XLAT0BzWtX7euHqmOYv/TJ243gvj9vVP/hZSG7ZvnkylyjaPt23Yi18Xy9JAnc9yKdp10w5L/v2lnDqD0AhtIdQ+U5M01LzR69OVVRZORSQf6IApfi3smm2g5fatCwy7KPdlYyKedMGCC9wyJ7iycJXdYaF4DRO8nn0LbxBdfnaO9ELDBVSSHPJh5T7Mdj8I6zqeGc9r0EvOgpn9nqtjBeaYZNAsDYSAE4066lfw7aUf3TD9PYHHYoRZb1SHKhDmy9YajuDmVUAoQspg3jQcx/t74FRZdNkaRTRjc6icZxWkRkr0udJ+cY6ocufUljdX+yTd8aLvsJUM250hOMEL5eRY2Unc+tXVszJ4UEEHa5XIGgcbeBCiFO/iTxxIrg/YMbMCeJysJtZcqRMQDUPiylTUMWMmySR3YIx3T0jQxxYepMd7PZs10u1jQJrfMMIW+Rn4BhGXpSdaaqnTV+r6R9BxOsKRx64eNiMakoghbYzzc=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-smtp-credentials
      namespace: monitoring
    type: Opaque
