apiVersion: v1
kind: Secret
metadata:
  name: flipkart-secrets
  namespace: flipkart
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-svc:27017/flipkart"
  CLOUDINARY_NAME: "demo"
  CLOUDINARY_API_KEY: "000000000000000"
  CLOUDINARY_API_SECRET: "dummy-secret-for-local-lab"
  JWT_SECRET: "gitops-lab-jwt-secret-key"
  JWT_EXPIRE: "5d"
  COOKIE_EXPIRE: "5"
